py/myadmin/urls.py
from django.conf.urls import url
from . views import views,userviews,typesviews,goodsviews,orderviews

urlpatterns = [
    # 后台首页
    url(r'^$', views.index,name='myadmin_index'),
    # 会员管理
    url(r'^user/add/$',userviews.add,name='myadmin_user_add'),
    url(r'^user/index/$',userviews.index,name='myadmin_user_list'),
    url(r'^user/delete/$',userviews.delete,name='myadmin_user_delete'),
    url(r'^user/edit/$',userviews.edit,name='myadmin_user_edit'),
    # 后台登录
    url(r'^user/login/$',userviews.login,name='myadmin_user_login'),
    url(r'^user/logout/$',userviews.logout,name='myadmin_user_logout'),
    # 订单管理
    url(r'^orders/index/$', orderviews.index,name='myadmin_orders_list'),

    # 商品分类管理
    url(r'^types/add/$',typesviews.add,name='myadmin_types_add'),
    url(r'^types/index/$',typesviews.index,name='myadmin_types_list'),
    url(r'^types/delete/$',typesviews.delete,name='myadmin_types_delete'),
    url(r'^types/edit/$',typesviews.edit,name='myadmin_types_edit'),


    # 商品管理
    url(r'^goods/add/$',goodsviews.add,name='myadmin_goods_add'),
    url(r'^goods/index/$',goodsviews.index,name='myadmin_goods_list'),
    url(r'^goods/delete/$',goodsviews.delete,name='myadmin_goods_delete'),
    url(r'^goods/edit/$',goodsviews.edit,name='myadmin_goods_edit'),






]

py/py/urls.py
from django.conf.urls import url,include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include('ueditor.urls')),
    url(r'^myadmin/',include('myadmin.urls')),
    url(r'^',include('myhome.urls')),
]

py/myadmin/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    username = models.CharField(max_length=50)
    # name = models.CharField(max_length=50)
    password = models.CharField(max_length=80)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=11)
    age = models.IntegerField(null=True)
    sex = models.CharField(max_length=1,null=True)
    pic = models.CharField(max_length=100,null=True)
    # 0 表示正常 1 表示禁用
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)


# 会员地址
class Address(models.Model):
    uid =  models.ForeignKey(to="Users", to_field="id")
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=20)
    xiangxi = models.CharField(max_length=50)
    status = models.IntegerField(default=0)


# 商品分类模型
class Types(models.Model):
    '''
        无限分类
            types 
                id name pid path 
                1  国家  0   0,
                2  品牌  1   0,1,
                3  本田  2   0,1,2,
                4  丰田  3   0,1,2,3,
    '''
    name = models.CharField(max_length=20)
    pid = models.IntegerField()
    path = models.CharField(max_length=50)

# 商品模型
class Goods(models.Model):
    # 一对多
    typeid = models.ForeignKey(to='Types',to_field='id')
    title = models.CharField(max_length=255)
    descr = models.CharField(max_length=255,null=True)
    info = models.TextField(null=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    pics = models.CharField(max_length=100)
    # 0为新发布 1为下架
    status = models.IntegerField(default=0)
    store = models.IntegerField(default=0)
    num = models.IntegerField(default=0)
    clicknum = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)


# 订单模型
class Orders(models.Model):
    uid = models.ForeignKey(to="Users", to_field="id")
    addressid = models.ForeignKey(to="Address", to_field="id")
    totalprice = models.FloatField()
    totalnum = models.IntegerField()
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True,null=True)

# 订单详情
class OrderInfo(models.Model):
    orderid = models.ForeignKey(to="Orders", to_field="id")
    gid = models.ForeignKey(to="Goods", to_field="id")
    num = models.IntegerField()

# 城市三级联动
class Citys(models.Model):
    # id name upid 
    name = models.CharField(max_length=100)
    upid = models.IntegerField()

    # myhome_citys
    class Meta():
        db_table = 'citys'

py/myadmin/views/orderviews.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
from  ..models import Orders
def index(request):
    #  找到所有订单
    orderlist = Orders.objects.all()

    # 导入分页类
    from django.core.paginator import Paginator
    # 实例化分页对象,参数1,数据集合,参数2 每页显示条数
    paginator = Paginator(orderlist, 10)
    # 获取当前页码数
    p = request.GET.get('p',1)
    # 获取当前页的数据
    orderlist = paginator.page(p)

    return render(request,'myadmin/order/list.html',{"orderlist":orderlist})

def edit(request):
    
    if request.method == "GET":

        orderid = request.GET.get("orderid",None)
        order = Orders.objects.get(id = orderid)

        return render(request,"myadmin/order/edit.html",{"order":order})
    elif request.method == "POST":
        pass

py/myadmin/views/typesviews.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,JsonResponse
from .. models import Types

# Create your views here.



def gettypesorder():
    # 获取所有的分类信息
    # tlist = Types.objects.all()

    # select * ,concat(path,id)as paths from myadmin_types order by paths;
    tlist = Types.objects.extra(select = {'paths':'concat(path,id)'}).order_by('paths')

    for x in tlist:
        if x.pid == 0:
            x.pname = '顶级分类'
        else:
            t = Types.objects.get(id=x.pid)
            x.pname = t.name
        num = x.path.count(',')-1
        x.name = (num*'<--->')+x.name

    return tlist
    


    
def add(request):
    if request.method == 'GET':
        # 返回一个添加的页面
        tlist = gettypesorder()

        context = {'tlist':tlist}

        return render(request,'myadmin/types/add.html',context)

    elif request.method == 'POST':
        # 执行分类的添加
        ob = Types()
        ob.name = request.POST['name']
        ob.pid = request.POST['pid']
        if ob.pid == '0':
            ob.path = '0,'
        else:
            # 根据当前父级id获取path,再添加当前父级id
            t = Types.objects.get(id=ob.pid)
            ob.path = t.path+str(ob.pid)+','
        ob.save()

        return HttpResponse('<script>alert("添加成功");location.href="'+reverse('myadmin_types_list')+'"</script>')



def index(request):
    
    tlist = gettypesorder()

    context = {'tlist':tlist}

    return render(request,'myadmin/types/list.html',context)




def delete(request):
    tid = request.GET.get('uid',None)
    print(tid)
    # 判断当前类下是否有子类
    num = Types.objects.filter(pid=tid).count()
    # print(num)
    if num != 0:
        data = {'msg':'当前类下有子类,不能删除','code':1}

    else:
        # 判断当前类下是否有商品
        ob = Types.objects.get(id=tid)
        ob.delete()
        data = {'msg':'删除成功','code':0}

    return JsonResponse(data)





def edit(request):
    # 显示修改和执行修改
    
    
    # 获取对象
    # ob = Goods.objects.get(id=uid)

    if request.method == 'GET':
        # 接收参数

        uid = request.GET.get('uid',None)
        print(uid)
        ob = Types.objects.filter()
        ob = ob.order_by('path')

        for x in ob:
            num = x.path.count(',')-1
            x.name = (num*'<--->')+x.name
        # 分配数据
        context = {'tlist':ob}
        # 显示编辑页面
        return render(request,'myadmin/types/edit.html',context)
        
    if request.method == 'POST':
        
        # uid = request.POST.get('uid',None)
        
        # name = request.POST.get('name',None)
        # print(uid,type(uid))
        # ob = Types.objects.get(id = uid)

        # ob.name = name
        # ob.path = ob.path
        # ob.pid = ob.pid

        # ob.save()

        return HttpResponse('<script>alert("修改成功");location.href="'+reverse('myadmin_types_list')+'"</script>')
        # except:
        #     return HttpResponse('<script>alert("修改失败");location.href="'+reverse('myadmin_goods_edit')+'?uid='+str(ob.id)+'"</script>')

py/myadmin/views/userviews.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,JsonResponse

from .. models import Users
import os
from django.contrib.auth.hashers import make_password,check_password
# Create your views here

# 会员列表
def index(request):

    # 获取搜索条件
    types = request.GET.get('type',None)
    keywords = request.GET.get('keywords',None)

    # 判断 是否具有搜索条件
    if types:
        # 有搜索条件的情况下
        if types == 'all':
            # 全条件搜索
            # 类似于 mysql中的:select * from user where username like "%张%"
            from django.db.models import Q
            userlist = Users.objects.filter(
                Q(username__contains=keywords)|
                Q(age__contains=keywords)|
                Q(email__contains=keywords)|
                Q(phone__contains=keywords)|
                Q(sex__contains=keywords)
            )
        elif types == 'username':
            # 按照用户名搜索
            userlist = Users.objects.filter(username__contains=keywords)

        elif types == 'age':
            # 按照年龄搜索
            userlist = Users.objects.filter(age__contains=keywords)
        
        elif types == 'email':
            # 按照邮箱搜索
            userlist = Users.objects.filter(email__contains=keywords)
        
        elif types == 'phone':
            # 按照电话搜索
            userlist = Users.objects.filter(phone__contains=keywords)

        elif types == 'sex':
            # 按照性别搜索
            userlist = Users.objects.filter(sex__contains=keywords)

    else:
        # 获取所有用户的数据
        userlist = Users.objects.filter()

    # print(44444)
    
        # 判断排序条件
        # userlist = userlist.order_by('-id')

    # 导入分页类
    from django.core.paginator import Paginator
    # 实例化分页对象 参数1 数据集合,参数2 每页显示的条数
    paginator = Paginator(userlist,10)
    # 获取当前的页码数
    p = request.GET.get('p',1)
    # 获取当前页的数据
    ulist = paginator.page(p)

        # 分配数据
    context = {'userlist':ulist}

        # 加载模版
    return render(request,'myadmin/user/list.html',context)






    # # 获取所有的用户数据
    # userlist = Users.objects.all()[:10]
    # # 分配数据
    # context = {'userlist':userlist}
    # # 加载模版
    # return render(request,'myadmin/user/list.html',context)
# 后台会员登录
def login(request):
    if request.method == "GET":

        return render(request,"myadmin/login.html")

    elif request.method == "POST":
        
        username = request.POST.get('username',None)

        # if username:

        #     user = Users.objects.filter(username = username)
        #     if not user:
        #         return HttpResponse("滚回去")

        #     if user.password\ 
        ob = Users.objects.get(username = request.POST['username'])
        # 检测密码是否正确
        res = check_password(request.POST['password'],ob.password)
        if res:
            # 密码正确 大于2就是后台的人员
            if ob.status >= 2:
                request.session['AdminUser'] = {'uid':ob.id,'username':ob.username}
                return HttpResponse('<script>alert("登录成功");location.href="/myadmin"</script>')
            else:

                return HttpResponse('<script>alert("权限不够，不允许登录");location.href="myadmin/login"</script>')
        else:
            return HttpResponse('<script>alert("用户名或密码错误！");location.href="myadmin/login"</script>')


# 后台退出
def logout(request):
    data = {}
    request.session['AdminUser'] = data

    return HttpResponse("<script>location.href='"+reverse("myadmin_user_login")+"'</script>")
# 会员添加
def add(request):
    if request.method == 'GET':
        # 显示添加页面
        return render(request,'myadmin/user/add.html')
    elif request.method == 'POST':
        # 执行用户数据添加 
        try:
            # 接收表单提交的数据
            data = request.POST.copy().dict()
            # 删除掉 csrf验证的字段数据
            del data['csrfmiddlewaretoken']
            # 进行密码加密
            from django.contrib.auth.hashers import make_password,check_password
            data['password'] = make_password(data['password'],None,'pbkdf2_sha256')
            # 进行用户头像上传
            if request.FILES.get('pic',None):
                data['pic'] = uploads(request)
                if data['pic'] == 1:
                    return HttpResponse('<script>alert("上传的文件不符合要求");location.href="'+reverse('myadmin_user_add')+'"</script>')
            else:
                del data['pic']

            # 执行用户的创建
            ob = Users.objects.create(**data)

            return HttpResponse('<script>alert("添加成功");location.href="'+reverse('myadmin_user_list')+'"</script>')
        except:    
            return HttpResponse('<script>alert("添加失败");location.href="'+reverse('myadmin_user_add')+'"</script>')

# 会员删除
def delete(request):
    try:
        uid = request.GET.get('uid',None)
        ob = Users.objects.get(id=uid)

        # 判断当前用户是否有头像 如果有的话执行删除
        if ob.pic:
            os.remove('.'+ob.pic)

        ob.delete()
        
        data = {'msg':'删除成功','code':0}
        
    except:
        data = {'msg':'删除失败','code':1}

    return JsonResponse(data)


# 显示修改和执行修改
def edit(request):
    # 接收参数
    uid = request.GET.get('uid',None)
    # 获取对象
    ob = Users.objects.get(id=uid)

    if request.method == 'GET':
        # 分配数据
        context = {'uinfo':ob}
        # 显示编辑页面
        return render(request,'myadmin/user/edit.html',context)

    elif request.method == 'POST':

        try:
            # 判断是否上传了新的图片
            if request.FILES.get('pic',None):
                if ob.pic:
                    # 如果使用的不是默认图 则删除之前上传的头像
                    os.remove('.'+ob.pic)

                # 执行上传
                ob.pic = uploads(request)

            ob.username = request.POST['username']
            ob.email = request.POST['email']
            ob.age = request.POST['age']
            ob.sex = request.POST['sex']
            ob.phone = request.POST['phone']
            ob.save()

            return HttpResponse('<script>alert("修改成功");location.href="'+reverse('myadmin_user_list')+'"</script>')
        except:
            return HttpResponse('<script>alert("修改失败");location.href="'+reverse('myadmin_user_edit')+'?uid='+str(ob.id)+'"</script>')

# 执行文件的上传 
def uploads(request):
    # 获取请求中的 文件 File
    myfile = request.FILES.get('pic',None)
    # 获取上传文件的后缀名 myfile.name.split('.').pop
    p = myfile.name.split('.').pop()
    arr = ['jpg','png','jpeg','gif']
    if p not in arr:
        return 2333

    import time,random
    # 生成新的文件名
    filename = str(time.time())+str(random.randint(1,9999))+'.'+p
    # 打开文件
    destination = open('./static/pics/'+filename,'wb+')
    # 分块写入文件
    for chunk in myfile.chunks():
        destination.write(chunk)
        # destination.write(myfile.read()) 不推荐使用

        # 关闭文件
        destination.close()

        return '/static/pics/'+filename

py/myadmin/views/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    

    return render(request,'myadmin/index.html')

py/templates/myadmin/order/list.html
{% extends 'myadmin/public/base.html' %}

{% block title %}
<title>后台订单列表</title>
{% endblock %}

{% block header %}
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-9">
            <div class="page-header-heading">
                <span class="am-icon-home page-header-heading-icon"></span> 
                订单列表 <small>Amaze UI</small>
            </div>
        </div>
    </div>
{% endblock %}


{% block con %}
<div class="row-content am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title  am-cf">商品订单列表</div>


                </div>
                <div class="widget-body  am-fr">

                    <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                        <div class="am-form-group">
                            <div class="am-btn-toolbar">
                                <div class="am-btn-group am-btn-group-xs">
                                    <button type="button" class="am-btn am-btn-default am-btn-success"><span class="am-icon-plus"></span> 新增</button>
                                    <button type="button" class="am-btn am-btn-default am-btn-secondary"><span class="am-icon-save"></span> 保存</button>
                                    <button type="button" class="am-btn am-btn-default am-btn-warning"><span class="am-icon-archive"></span> 审核</button>
                                    <button type="button" class="am-btn am-btn-default am-btn-danger"><span class="am-icon-trash-o"></span> 删除</button>
                                </div>
                            </div>
                        </div>
                    </div>

                <form>
                    <div class="am-u-sm-12 am-u-md-6 am-u-lg-3">
                        <div class="am-form-group tpl-table-list-select">
                            <select name="type" data-am-selected="{btnSize: 'sm'}" style="display: none;">
                              <option value="all" {% if request.GET.type == 'all' %} selected {% endif %} >所有条件</option>
                              <option value="username" {% if request.GET.type == 'username' %} selected {% endif %} >姓名</option>
                              <option value="age" {% if request.GET.type == 'age' %} selected {% endif %} >年龄</option>
                              <option value="email" {% if request.GET.type == 'email' %} selected {% endif %} >邮箱</option>
                              <option value="phone" {% if request.GET.type == 'phone' %} selected {% endif %} >手机号</option>
                              <option value="sex" {% if request.GET.type == 'sex' %} selected {% endif %} >性别</option>
                            </select>
                        </div>
                    </div>
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
                        <div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">
                            <input type="text" name="keywords" class="am-form-field " value="{{ request.GET.keywords }}">
                            <span class="am-input-group-btn">
                            <button class="am-btn  am-btn-default am-btn-success tpl-table-list-field am-icon-search"></button>
                          </span>
                        </div>
                    </div>
                </form>


                    <div class="am-u-sm-12">
                        <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black ">
                            <thead>
                                <tr>
                                    <th>订单编号</th>
                                    <th>图片</th>
                                    <th>商品</th>
                                    <th>单价</th>
                                    <th>数量</th>
                                    <th>总价</th>
                                    <th>状态</th>
                                    <th>订单时间</th>
                                    <th>用户</th>
                                    <th>地址</th>
                                    <th>操作</th>
                                    
                                    
                                </tr>
                            </thead>
                            <tbody>
                            <!-- 遍历所有的订单 -->
                            {% for v in orderlist %}
                                <tr>
                                    <!-- 通过遍历 找到orderinfo的详情  -->
                                    {% for goods in v.orderinfo_set.all %}
                                    <td class="am-text-middle">{{ v.id }}</td>
                                    <td>
                                        <img src="{{ goods.gid.pics }}" class="tpl-table-line-img" alt="">
                                    </td>
                                    <td class="am-text-middle">{{ goods.gid.title }}</td>
                                    <td class="am-text-middle">{{ goods.gid.price }}</td>
                                    <td class="am-text-middle">{{ goods.num }}</td>
                                    <td class="am-text-middle">{{ v.totalprice }}</td>
                                    <td class="am-text-middle">
                                        {% if v.status == 0 %}
                                        未付款
                                        {% elif v.status == 1 %}
                                        未发货
                                        {% elif v.status == 2 %}
                                        未收货
                                        {% elif v.status == 3 %}
                                        未评价
                                        {% endif %}
                                    </td>
                                    <td class="am-text-middle">{{ v.addtime|date:"Y-m-d H:i:s" }}</td>
                                    <td class="am-text-middle">{{ v.uid.username }}</td>
                                    <td class="am-text-middle">{{ v.addressid.address }}</td>
                                    
                                    
                                    
                                    <td class="am-text-middle">
                                        <div class="tpl-table-black-operation">
                                            <a href="#">
                                                <i class="am-icon-pencil"></i> 修改订单状态
                                            </a>
                                           
                                        </div>
                                    </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        
                                <!-- more data -->
                            </tbody>
                        </table>
                    </div>
                    <div class="am-u-lg-12 am-cf">
                        <div class="am-fr">
                            <ul class="am-pagination tpl-pagination">
                           <!--      <li class="am-disabled"><a href="#">«</a></li>
                                <li class="am-active"><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#">»</a></li> -->
                                {% load pagetag %}

                                {% PageShow orderlist.paginator.num_pages request %}    
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    // 删除
    $('.tpl-table-black-operation-del').click(function(){

        id = $(this).parents('tr').find('td:eq(0)').text()
        a = $(this)

        $.get("{% url 'myadmin_types_delete' %}",{uid:id},function(data){
            alert(data.msg)
            if(data.code == 0){
                // 成功,移动当前这一条数据
                // $(this).parents('tr').remove() // x 
                // $(this)在此处,代表的是ajax对象 XMLHttpRequest
                a.parents('tr').remove() 
            }

        },'json')
    })
</script>
{% endblock%}